#!/usr/bin/env bash
# Regenerates docs/bug_gallery_transcript.md by actually running `phase
# check` against every file under examples/bug_gallery/ and the two happy
# paths, and capturing the real output. This is never hand-typed -- run
# this script again after any change to the analyzer and the transcript
# stays truthful.
#
# Run from the phase/ project root:
#   ./scripts/capture_bug_gallery.sh

set -euo pipefail
cd "$(dirname "$0")/.."   # phase/ project root

OUT="docs/bug_gallery_transcript.md"
cargo build -q --bin phase
BIN="target/debug/phase"

{
  echo "# Bug Gallery Transcript"
  echo
  echo "Generated by \`scripts/capture_bug_gallery.sh\` -- every block below is"
  echo "the real, unedited output of \`phase check\` run against the file named"
  echo "above it. Regenerate after any analyzer change with:"
  echo
  echo '```'
  echo "./scripts/capture_bug_gallery.sh"
  echo '```'
  echo
  echo "## Happy paths (expected to pass)"
  echo

  for f in examples/radio_pipeline.phase examples/packet_pipeline.phase \
           examples/branching_pipeline.phase examples/mmio_registers.phase \
           examples/sdr_session.phase; do
    echo "### \`$f\`"
    echo
    echo '```'
    "$BIN" check "$f" 2>&1 || true
    echo '```'
    echo
  done

  echo "## Bug gallery (expected to fail, with the exact compiler output)"
  echo

  for f in examples/bug_gallery/*.phase; do
    echo "### \`$f\`"
    echo
    # pull out the leading `//` comment block as a one-line description
    desc=$(grep '^//' "$f" | head -1 | sed 's#^// ##')
    echo "$desc"
    echo
    echo '```'
    "$BIN" check "$f" 2>&1 || true
    echo '```'
    echo
  done
} > "$OUT"

echo "Wrote $OUT"
