//! PHASE M5: lowers PIR (phase_pir) to C source text (spec §6).
//!
//! Produces two strings per program: a header (struct typedefs + extern-fn
//! prototypes, meant to be shared with hand-written runtime glue like
//! `runtime/phase_runtime.c`) and a source file (the actual PHASE function
//! bodies). See spec §6.1-§6.2 for why C, not LLVM, and why buffers are
//! plain stack arrays in this simulation model.

use phase_ast::{BorrowMode, Domain};
use phase_pir::{CallArg, PirEntityDef, PirFn, PirFnSig, PirInst, PirLiteral, PirProgram, PirType};
use std::collections::HashMap;

pub struct Generated {
    pub header: String,
    pub source: String,
}

/// `stem` becomes both the `#ifndef` guard and the `#include` name the
/// generated source uses for its own header (e.g. `"radio_pipeline"` ->
/// `radio_pipeline.gen.h`, guard `PHASE_GEN_RADIO_PIPELINE_H`).
pub fn generate(program: &PirProgram, stem: &str) -> Generated {
    Generated {
        header: generate_header(program, stem),
        source: generate_source(program, stem),
    }
}

// ---- type formatting ------------------------------------------------------

/// The type name usable in a *non-declarator* context (return types,
/// buffer element types nested inside a struct field's own declarator,
/// etc). Not valid on its own for a buffer variable -- see `declare`.
fn type_name(ty: &PirType) -> String {
    match ty {
        PirType::Scalar(s) => s.clone(),
        PirType::Named(n) => n.clone(),
        PirType::Buffer { elem, .. } => type_name(elem),
    }
}

/// Emit a full C declaration for a named variable/field of the given PIR
/// type, handling the array-declarator wrapping C requires for buffers
/// (`Sample name[1024];`, not `buffer<Sample,1024> name;`).
fn declare(name: &str, ty: &PirType) -> String {
    match ty {
        PirType::Buffer { elem, len } => format!("{} {}[{}]", type_name(elem), name, len),
        other => format!("{} {}", type_name(other), name),
    }
}

// ---- header: struct typedefs + extern fn prototypes -----------------------

fn generate_header(program: &PirProgram, stem: &str) -> String {
    let guard = format!("PHASE_GEN_{}_H", stem.to_uppercase());
    let mut out = String::new();
    out.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    out.push_str("#include <stdint.h>\n#include <stddef.h>\n#include <stdbool.h>\n\n");

    if !program.entities.is_empty() {
        out.push_str("/* --- entity struct definitions (from `entity` declarations) --- */\n\n");
        for e in &program.entities {
            out.push_str(&format_struct(e));
            out.push('\n');
        }
    }

    if !program.extern_fns.is_empty() {
        out.push_str("/* --- extern fn prototypes ---\n");
        out.push_str(" * PHASE `extern fn` declares a trusted, opaque operation implemented\n");
        out.push_str(" * elsewhere (e.g. runtime/phase_runtime.c for this demo) -- the compiler\n");
        out.push_str(" * only emits a matching prototype here, never a body.\n");
        out.push_str(" * Convention: every `buffer<T,N>` argument gets a trailing `size_t ..._len`\n");
        out.push_str(" * parameter carrying its compile-time-known element count.\n */\n\n");
        for f in &program.extern_fns {
            out.push_str(&format_fn_prototype(f));
            out.push_str(";\n");
        }
        out.push('\n');
    }

    out.push_str(&format!("#endif /* {guard} */\n"));
    out
}

fn format_struct(e: &PirEntityDef) -> String {
    let mut s = "typedef struct {\n".to_string();
    for (fname, fty) in &e.fields {
        s.push_str(&format!("    {};\n", declare(fname, fty)));
    }
    s.push_str(&format!("}} {};\n", e.name));
    s
}

fn format_fn_prototype(sig: &PirFnSig) -> String {
    let ret = sig
        .return_type
        .as_ref()
        .map(type_name)
        .unwrap_or_else(|| "void".to_string());
    let params = format_params(&sig.params);
    format!("{ret} {}({params})", sig.name)
}

fn format_params(params: &[(String, PirType)]) -> String {
    if params.is_empty() {
        return "void".to_string();
    }
    let mut parts = Vec::new();
    for (name, ty) in params {
        match ty {
            PirType::Buffer { elem, .. } => {
                parts.push(format!("{}* {}", type_name(elem), name));
                parts.push(format!("size_t {}_len", name));
            }
            other => parts.push(declare(name, other)),
        }
    }
    parts.join(", ")
}

// ---- source: PHASE fn bodies -----------------------------------------------

fn generate_source(program: &PirProgram, stem: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("#include \"{stem}.gen.h\"\n"));
    out.push_str("#include \"phase_runtime.h\"\n\n");
    out.push_str("/* Generated by the PHASE compiler (M5). Do not edit by hand. */\n\n");

    // name -> signature, for both extern fns and other PHASE fns, so a
    // call site knows whether to append a `_len` argument for a buffer.
    let mut sigs: HashMap<&str, &PirFnSig> = HashMap::new();
    for f in &program.extern_fns {
        sigs.insert(f.name.as_str(), f);
    }
    for f in &program.fns {
        sigs.insert(f.sig.name.as_str(), &f.sig);
    }

    for f in &program.fns {
        out.push_str(&format_fn(f, &sigs));
        out.push('\n');
    }

    out
}

fn format_fn(f: &PirFn, sigs: &HashMap<&str, &PirFnSig>) -> String {
    let is_main = f.sig.name == "main";
    let (ret, name, params) = if is_main {
        ("int".to_string(), "main".to_string(), "void".to_string())
    } else {
        let ret = f
            .sig
            .return_type
            .as_ref()
            .map(type_name)
            .unwrap_or_else(|| "void".to_string());
        (ret, f.sig.name.clone(), format_params(&f.sig.params))
    };

    let mut out = format!("{ret} {name}({params}) {{\n");
    let mut locals: HashMap<String, PirType> = HashMap::new();
    for (pname, pty) in &f.sig.params {
        locals.insert(pname.clone(), pty.clone());
    }
    for inst in &f.body {
        out.push_str(&format_inst(inst, sigs, &mut locals));
    }
    if is_main {
        out.push_str("    return 0;\n");
    }
    out.push_str("}\n");
    out
}

fn format_inst(
    inst: &PirInst,
    sigs: &HashMap<&str, &PirFnSig>,
    locals: &mut HashMap<String, PirType>,
) -> String {
    match inst {
        PirInst::EntityCreate { name, ty, .. } => {
            locals.insert(name.clone(), ty.clone());
            format!("    {};\n", declare(name, ty))
        }

        PirInst::EntityCreateWithFields {
            name, ty, fields, ..
        } => {
            locals.insert(name.clone(), ty.clone());
            let inits: Vec<String> = fields
                .iter()
                .map(|(fname, lit)| format!(".{fname} = {}", format_literal(lit)))
                .collect();
            format!("    {} = {{ {} }};\n", declare(name, ty), inits.join(", "))
        }

        PirInst::CallAssign {
            name,
            ty,
            callee,
            args,
            ..
        } => {
            locals.insert(name.clone(), ty.clone());
            let call_sig = sigs.get(callee.as_str()).copied();
            let arg_text = format_args(args, call_sig, locals);
            format!("    {} = {}({});\n", declare(name, ty), callee, arg_text)
        }

        PirInst::EntityMove { name, to } => format!(
            "    /* move {name} -> @{} (compile-time only; the v0.1 simulation model keeps everything in one address space, so there is nothing to physically move) */\n",
            to.name()
        ),

        PirInst::EntitySync { name, from } => {
            let wait_fn = match from {
                Domain::Dma => "sim_dma_wait",
                Domain::Device => "sim_device_wait",
                // The M2 analyzer guarantees `sync` is only legal from
                // Dma/Device; anything else here is unreachable in a
                // program that passed analysis, but fall back safely.
                _ => "sim_device_wait",
            };
            format!(
                "    {wait_fn}(\"{name}\", {name}, sizeof({name}));\n"
            )
        }

        PirInst::EntityBorrow { name, target, mode } => {
            let target_ty = locals.get(target).cloned();
            let (elem_ty, is_buffer) = match &target_ty {
                Some(PirType::Buffer { elem, .. }) => (type_name(elem), true),
                Some(other) => (type_name(other), false),
                None => ("void".to_string(), false),
            };
            let const_kw = match mode {
                BorrowMode::Read => "const ",
                BorrowMode::Write => "",
            };
            let ptr_ty = format!("{const_kw}{elem_ty}*");
            locals.insert(name.clone(), target_ty.unwrap_or(PirType::Scalar("void".into())));
            if is_buffer {
                format!("    {ptr_ty} {name} = {target}; /* borrow */\n")
            } else {
                format!("    {ptr_ty} {name} = &{target}; /* borrow */\n")
            }
        }

        PirInst::EntityRelease { name } => {
            format!("    /* release {name} (compile-time only; no separate runtime action) */\n")
        }

        PirInst::EntityDestroy { name } => format!(
            "    /* destroy {name} (compile-time only; buffers are stack-allocated in v0.1, so there is no separate deallocation step) */\n"
        ),

        PirInst::Call { callee, args } => {
            let call_sig = sigs.get(callee.as_str()).copied();
            let arg_text = format_args(args, call_sig, locals);
            format!("    {callee}({arg_text});\n")
        }

        PirInst::Return { value } => match value {
            Some(v) => format!("    return {v};\n"),
            None => "    return;\n".to_string(),
        },
    }
}

fn format_args(
    args: &[CallArg],
    sig: Option<&PirFnSig>,
    locals: &HashMap<String, PirType>,
) -> String {
    let mut parts = Vec::new();
    for (i, a) in args.iter().enumerate() {
        match a {
            CallArg::Entity(name) => {
                parts.push(name.clone());
                // Append the compile-time element count for any argument
                // whose *declared parameter* is a buffer -- matches the
                // trailing `size_t ..._len` convention in format_params.
                let param_is_buffer = sig
                    .and_then(|s| s.params.get(i))
                    .map(|(_, ty)| matches!(ty, PirType::Buffer { .. }))
                    .unwrap_or(false);
                if param_is_buffer {
                    if let Some(PirType::Buffer { len, .. }) = locals.get(name) {
                        parts.push(len.to_string());
                    } else {
                        parts.push(format!("sizeof({name})/sizeof({name}[0])"));
                    }
                }
            }
            CallArg::Literal(lit) => parts.push(format_literal(lit)),
        }
    }
    parts.join(", ")
}

fn format_literal(lit: &PirLiteral) -> String {
    match lit {
        PirLiteral::Int(n) => n.to_string(),
        PirLiteral::Float(n) => format!("{n}f"),
        PirLiteral::Str(s) => format!("{s:?}"),
        PirLiteral::Bool(b) => b.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generate_src(src: &str, stem: &str) -> Generated {
        let program = phase_parser::parse(src).expect("fixture must parse");
        phase_analysis::analyze(&program).expect("fixture must pass analysis");
        let pir = phase_pir::build(&program).expect("fixture must lower to PIR");
        generate(&pir, stem)
    }

    #[test]
    fn struct_is_emitted_in_header() {
        let g = generate_src("entity Sample : @RAM { value: f32 } fn main() {}", "t");
        assert!(g.header.contains("typedef struct {"));
        assert!(g.header.contains("float value;"));
        assert!(g.header.contains("} Sample;"));
    }

    #[test]
    fn extern_fn_prototype_appends_len_params_for_buffers() {
        let src = "extern fn f(a: buffer<u8, 4> @RAM); fn main() {}";
        let g = generate_src(src, "t");
        assert!(g.header.contains("void f(uint8_t* a, size_t a_len);"));
    }

    #[test]
    fn main_becomes_c_int_main_with_implicit_return() {
        let g = generate_src("fn main() { buffer<u8, 4> x @RAM; }", "t");
        assert!(g.source.contains("int main(void) {"));
        assert!(g.source.contains("uint8_t x[4];"));
        assert!(g.source.contains("return 0;"));
    }

    #[test]
    fn buffer_call_argument_gets_trailing_length() {
        let src = r#"
            extern fn f(a: buffer<u8, 4> @RAM);
            fn main() {
                buffer<u8, 4> x @RAM;
                f(x);
            }
        "#;
        let g = generate_src(src, "t");
        assert!(g.source.contains("f(x, 4);"));
    }

    #[test]
    fn sync_from_dma_calls_sim_dma_wait() {
        let src = r#"
            extern fn cap(x: buffer<u8, 4> @DMA);
            fn main() {
                buffer<u8, 4> x @DMA;
                cap(x);
                sync(x);
            }
        "#;
        let g = generate_src(src, "t");
        assert!(g.source.contains("sim_dma_wait(\"x\", x, sizeof(x));"));
    }

    #[test]
    fn sync_from_device_calls_sim_device_wait() {
        let src = r#"
            extern fn play(x: buffer<u8, 4> @DEVICE);
            fn main() {
                buffer<u8, 4> x @RAM;
                move x -> @DEVICE;
                play(x);
                sync(x);
            }
        "#;
        let g = generate_src(src, "t");
        assert!(g.source.contains("sim_device_wait(\"x\", x, sizeof(x));"));
    }

    #[test]
    fn move_becomes_an_explanatory_comment_not_a_statement() {
        let src = r#"
            fn main() {
                buffer<u8, 4> x @RAM;
                move x -> @DMA;
            }
        "#;
        let g = generate_src(src, "t");
        assert!(g.source.contains("/* move x -> @DMA"));
    }

    #[test]
    fn struct_lit_init_uses_designated_initializer() {
        let src = "entity Sample : @RAM { value: f32 } fn main() { let s: Sample @RAM = Sample { value: 2.5 }; }";
        let g = generate_src(src, "t");
        assert!(g.source.contains("Sample s = { .value = 2.5f };"));
    }

    #[test]
    fn header_include_guard_and_source_include_use_the_same_stem() {
        let g = generate_src("fn main() {}", "radio_pipeline");
        assert!(g.header.contains("PHASE_GEN_RADIO_PIPELINE_H"));
        assert!(g.source.contains("#include \"radio_pipeline.gen.h\""));
    }

    #[test]
    fn full_radio_pipeline_shaped_program_generates_plausible_c() {
        let src = r#"
            entity Sample : @RAM { value: f32 }
            extern fn fir_filter(in_: buffer<Sample, 4> @RAM, out: buffer<Sample, 4> @RAM);
            extern fn device_capture(dst: buffer<Sample, 4> @DMA);
            extern fn device_playback(src: buffer<Sample, 4> @DEVICE);
            fn main() {
                buffer<Sample, 4> raw @DMA;
                device_capture(raw);
                sync(raw);
                buffer<Sample, 4> filtered @RAM;
                fir_filter(raw, filtered);
                move filtered -> @DEVICE;
                device_playback(filtered);
                sync(filtered);
            }
        "#;
        let g = generate_src(src, "radio_pipeline");
        assert!(g.source.contains("device_capture(raw, 4);"));
        assert!(g.source.contains("sim_dma_wait(\"raw\", raw, sizeof(raw));"));
        assert!(g.source.contains("fir_filter(raw, 4, filtered, 4);"));
        assert!(g.source.contains("device_playback(filtered, 4);"));
        assert!(g.source.contains("sim_device_wait(\"filtered\", filtered, sizeof(filtered));"));
    }
}
